name: geo_binder
channels:
  - conda-forge
  - defaults
dependencies:
  - dask
  - pysal
  - geopandas
  - jupyter
  - rasterio
  - xarray
  - descartes
  - osmnx
  - folium
  - geopy
  - plotly
  - sklearn
  - scikit-image
  - matplotlib
  - geoplot
  - networkx
  - osmnx
  - descartes
  - contextily
  - shapefile
  - sentinelsat
  - numpy